version: '3'

services:
  heimdall:
    image: linuxserver/heimdall
    ports:
      - 40080:80
    volumes:
      - ./config:/config
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Seoul
    restart: always