version: '3'

services: 
  geoserver:
    image: bitnami/tomcat:${TOMCAT_VERSION}
    ports: 
      - ${TOMCAT_PORT}:8080
    volumes: 
      - ./conf/catalina.sh:/opt/bitnami/tomcat/bin/catalina.sh
      
      - ./webapps/ROOT:/opt/bitnami/tomcat/webapps_default/ROOT
      - ./webapps/geoserver:/opt/bitnami/tomcat/webapps_default/geoserver