version: '3.3'

services:
  traefik:
    image: traefik # The official Traefik docker image
    command:
      - --providers.docker.exposedbydefault=false
    environment:
      TRAEFIK_ACCESSLOG: true
      # TRAEFIK_METRICS_PROMETHEUS: true
      TRAEFIK_API_INSECURE: true # The Web UI
      TRAEFIK_PROVIDERS_DOCKER: true
    labels:
      traefik.http.routers.traefik.rule: Host(`traefik.service.localhost`)
      traefik.http.routers.traefik.service: api@internal
    ports:
      - 8081:8080 # The Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  portainer:
    image: portainer/portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true

  whoami:
    image: traefik/whoami
    container_name: simple-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=web