version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - 8069:8069
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
