version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    restart: always
    ports:
      - 9080:8080
      - 50010:50000
    expose:
      - 8080
      - 50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
    environment:
      TZ: Asia/Seoul