version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.14.0
    container_name: portainer
    restart: always
    ports:
      - 8880:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

volumes:
  portainer_data:
