version: '3.5'

services:
  postgis:
    build: 
      context: .
      args:
        POSTGIS_VERSION: ${POSTGIS_VERSION}
    # image: postgis/postgis:${POSTGIS_VERSION}
    command: postgres -c max_connections=${PG_MAX_CONNECTIONS} -c shared_buffers=${PG_SHARED_BUFFERS}
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./mecab/ts_mecab_ko.sql:/textsearch_ko/ts_mecab_ko.sql
      - ./mecab/ld.so.conf:/etc/ld.so.conf
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      LOCALE: ${PGADMIN_LOCALE}
    volumes:
      - pgadmin:/root/.pgadmin
      - ./pgadmin-data:/tmp
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - postgis
    restart: unless-stopped

networks:
  postgis:
    driver: bridge

volumes:
    pgadmin:
    pgadmin-data: