version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass ${PASSWORD} --port 6379
    restart: always
    user: root
    ports:
      - ${PORT}:6379
    environment:
      TZ: 'Asia/Seoul'